package fei.tools.dc.po;

// Generated Dec 17, 2010 2:03:35 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestTblTmsMsg generated by hbm2java
 */
@Entity
@Table(name = "TblTmsMsg", schema= "dbo", catalog = "pbOnline")
public class TblTmsMsg implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private TblTmsMsgId id;
	private int msgId;
	private String subAcct;
	private char msgOp;
	private char msgState;
	private String tmsId;
	private String tmsTime;
	private String tmsMsg1;
	private String tmsMsg2;
	private String tmsMsg3;
	private String tmsMsg4;
	private String tmsMsg5;
	private Date auditDate;
	private Character pnsDtc;

	public TblTmsMsg() {
	}

	public TblTmsMsg(TblTmsMsgId id, int msgId, String subAcct,
			char msgOp, char msgState, String tmsId, String tmsTime,
			String tmsMsg1, String tmsMsg2, String tmsMsg3, String tmsMsg4,
			String tmsMsg5, Date auditDate) {
		this.id = id;
		this.msgId = msgId;
		this.subAcct = subAcct;
		this.msgOp = msgOp;
		this.msgState = msgState;
		this.tmsId = tmsId;
		this.tmsTime = tmsTime;
		this.tmsMsg1 = tmsMsg1;
		this.tmsMsg2 = tmsMsg2;
		this.tmsMsg3 = tmsMsg3;
		this.tmsMsg4 = tmsMsg4;
		this.tmsMsg5 = tmsMsg5;
		this.auditDate = auditDate;
	}

	public TblTmsMsg(TblTmsMsgId id, int msgId, String subAcct,
			char msgOp, char msgState, String tmsId, String tmsTime,
			String tmsMsg1, String tmsMsg2, String tmsMsg3, String tmsMsg4,
			String tmsMsg5, Date auditDate, Character pnsDtc) {
		this.id = id;
		this.msgId = msgId;
		this.subAcct = subAcct;
		this.msgOp = msgOp;
		this.msgState = msgState;
		this.tmsId = tmsId;
		this.tmsTime = tmsTime;
		this.tmsMsg1 = tmsMsg1;
		this.tmsMsg2 = tmsMsg2;
		this.tmsMsg3 = tmsMsg3;
		this.tmsMsg4 = tmsMsg4;
		this.tmsMsg5 = tmsMsg5;
		this.auditDate = auditDate;
		this.pnsDtc = pnsDtc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tradeId", column = @Column(name = "tradeId", nullable = false)),
			@AttributeOverride(name = "tradeVer", column = @Column(name = "tradeVer", nullable = false)) })
	public TblTmsMsgId getId() {
		return this.id;
	}

	public void setId(TblTmsMsgId id) {
		this.id = id;
	}

	@Column(name = "msgId", nullable = false)
	public int getMsgId() {
		return this.msgId;
	}

	public void setMsgId(int msgId) {
		this.msgId = msgId;
	}

	@Column(name = "subAcct", nullable = false, length = 10)
	public String getSubAcct() {
		return this.subAcct;
	}

	public void setSubAcct(String subAcct) {
		this.subAcct = subAcct;
	}

	@Column(name = "msgOp", nullable = false, length = 1)
	public char getMsgOp() {
		return this.msgOp;
	}

	public void setMsgOp(char msgOp) {
		this.msgOp = msgOp;
	}

	@Column(name = "msgState", nullable = false, length = 1)
	public char getMsgState() {
		return this.msgState;
	}

	public void setMsgState(char msgState) {
		this.msgState = msgState;
	}

	@Column(name = "tmsId", nullable = false, length = 15)
	public String getTmsId() {
		return this.tmsId;
	}

	public void setTmsId(String tmsId) {
		this.tmsId = tmsId;
	}

	@Column(name = "tmsTime", nullable = false, length = 14)
	public String getTmsTime() {
		return this.tmsTime;
	}

	public void setTmsTime(String tmsTime) {
		this.tmsTime = tmsTime;
	}

	@Column(name = "tmsMsg1", nullable = false, length = 40)
	public String getTmsMsg1() {
		return this.tmsMsg1;
	}

	public void setTmsMsg1(String tmsMsg1) {
		this.tmsMsg1 = tmsMsg1;
	}

	@Column(name = "tmsMsg2", nullable = false, length = 40)
	public String getTmsMsg2() {
		return this.tmsMsg2;
	}

	public void setTmsMsg2(String tmsMsg2) {
		this.tmsMsg2 = tmsMsg2;
	}

	@Column(name = "tmsMsg3", nullable = false, length = 40)
	public String getTmsMsg3() {
		return this.tmsMsg3;
	}

	public void setTmsMsg3(String tmsMsg3) {
		this.tmsMsg3 = tmsMsg3;
	}

	@Column(name = "tmsMsg4", nullable = false, length = 40)
	public String getTmsMsg4() {
		return this.tmsMsg4;
	}

	public void setTmsMsg4(String tmsMsg4) {
		this.tmsMsg4 = tmsMsg4;
	}

	@Column(name = "tmsMsg5", nullable = false, length = 40)
	public String getTmsMsg5() {
		return this.tmsMsg5;
	}

	public void setTmsMsg5(String tmsMsg5) {
		this.tmsMsg5 = tmsMsg5;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "auditDate", nullable = false, length = 23)
	public Date getAuditDate() {
		return this.auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	@Column(name = "pnsDtc", length = 1)
	public Character getPnsDtc() {
		return this.pnsDtc;
	}

	public void setPnsDtc(Character pnsDtc) {
		this.pnsDtc = pnsDtc;
	}

}
