package fei.tools.dc.po;

// Generated Dec 17, 2010 2:03:35 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestTblIpbMsg generated by hbm2java
 */
@Entity
@Table(name = "TblIpbMsg", schema= "dbo", catalog = "pbOnline")
public class TblIpbMsg implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private TblIpbMsgId id;
	private char msgState;
	private String olyRef;
	private Date entryDt;
	private Date modDt;

	public TblIpbMsg() {
	}

	public TblIpbMsg(TblIpbMsgId id, char msgState, Date entryDt,
			Date modDt) {
		this.id = id;
		this.msgState = msgState;
		this.entryDt = entryDt;
		this.modDt = modDt;
	}

	public TblIpbMsg(TblIpbMsgId id, char msgState, String olyRef,
			Date entryDt, Date modDt) {
		this.id = id;
		this.msgState = msgState;
		this.olyRef = olyRef;
		this.entryDt = entryDt;
		this.modDt = modDt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tradeId", column = @Column(name = "tradeId", nullable = false)),
			@AttributeOverride(name = "tradeVer", column = @Column(name = "tradeVer", nullable = false)) })
	public TblIpbMsgId getId() {
		return this.id;
	}

	public void setId(TblIpbMsgId id) {
		this.id = id;
	}

	@Column(name = "msgState", nullable = false, length = 1)
	public char getMsgState() {
		return this.msgState;
	}

	public void setMsgState(char msgState) {
		this.msgState = msgState;
	}

	@Column(name = "olyRef", length = 32)
	public String getOlyRef() {
		return this.olyRef;
	}

	public void setOlyRef(String olyRef) {
		this.olyRef = olyRef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entryDt", nullable = false, length = 23)
	public Date getEntryDt() {
		return this.entryDt;
	}

	public void setEntryDt(Date entryDt) {
		this.entryDt = entryDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modDt", nullable = false, length = 23)
	public Date getModDt() {
		return this.modDt;
	}

	public void setModDt(Date modDt) {
		this.modDt = modDt;
	}

}
