package fei.tools.dc.po;

// Generated Dec 17, 2010 2:03:35 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestTblRadarMsg generated by hbm2java
 */
@Entity
@Table(name = "TblRadarMsg", schema= "dbo", catalog = "pbOnline")
public class TblRadarMsg implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private TblRadarMsgId id;
	private char msgOp;
	private char msgState;
	private String radarTime;
	private String radarMsg1;
	private String radarMsg2;
	private Date entryDt;
	private Date modDt;

	public TblRadarMsg() {
	}

	public TblRadarMsg(TblRadarMsgId id, char msgOp, char msgState,
			Date entryDt, Date modDt) {
		this.id = id;
		this.msgOp = msgOp;
		this.msgState = msgState;
		this.entryDt = entryDt;
		this.modDt = modDt;
	}

	public TblRadarMsg(TblRadarMsgId id, char msgOp, char msgState,
			String radarTime, String radarMsg1, String radarMsg2, Date entryDt,
			Date modDt) {
		this.id = id;
		this.msgOp = msgOp;
		this.msgState = msgState;
		this.radarTime = radarTime;
		this.radarMsg1 = radarMsg1;
		this.radarMsg2 = radarMsg2;
		this.entryDt = entryDt;
		this.modDt = modDt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tradeId", column = @Column(name = "tradeId", nullable = false)),
			@AttributeOverride(name = "tradeVer", column = @Column(name = "tradeVer", nullable = false)) })
	public TblRadarMsgId getId() {
		return this.id;
	}

	public void setId(TblRadarMsgId id) {
		this.id = id;
	}

	@Column(name = "msgOp", nullable = false, length = 1)
	public char getMsgOp() {
		return this.msgOp;
	}

	public void setMsgOp(char msgOp) {
		this.msgOp = msgOp;
	}

	@Column(name = "msgState", nullable = false, length = 1)
	public char getMsgState() {
		return this.msgState;
	}

	public void setMsgState(char msgState) {
		this.msgState = msgState;
	}

	@Column(name = "radarTime", length = 15)
	public String getRadarTime() {
		return this.radarTime;
	}

	public void setRadarTime(String radarTime) {
		this.radarTime = radarTime;
	}

	@Column(name = "radarMsg1", length = 40)
	public String getRadarMsg1() {
		return this.radarMsg1;
	}

	public void setRadarMsg1(String radarMsg1) {
		this.radarMsg1 = radarMsg1;
	}

	@Column(name = "radarMsg2", length = 40)
	public String getRadarMsg2() {
		return this.radarMsg2;
	}

	public void setRadarMsg2(String radarMsg2) {
		this.radarMsg2 = radarMsg2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entryDt", nullable = false, length = 23)
	public Date getEntryDt() {
		return this.entryDt;
	}

	public void setEntryDt(Date entryDt) {
		this.entryDt = entryDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modDt", nullable = false, length = 23)
	public Date getModDt() {
		return this.modDt;
	}

	public void setModDt(Date modDt) {
		this.modDt = modDt;
	}

}
