// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package test.basic.rmi.hello;

public final class HelloImpl_Stub
    extends java.rmi.server.RemoteStub
    implements test.basic.rmi.hello.Hello, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getSet_0;
    private static java.lang.reflect.Method $method_sayHello_1;
    
    static {
	try {
	    $method_getSet_0 = test.basic.rmi.hello.Hello.class.getMethod("getSet", new java.lang.Class[] {});
	    $method_sayHello_1 = test.basic.rmi.hello.Hello.class.getMethod("sayHello", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public HelloImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getSet()
    public java.util.Set getSet()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSet_0, null, -7552305175428573883L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sayHello()
    public java.lang.String sayHello()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHello_1, null, 6043973830760146143L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
