// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package test.basic.basic.rmi.product;

public final class ProductImpl_Stub
    extends java.rmi.server.RemoteStub
    implements test.basic.basic.rmi.product.Product, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getDescription_0;
    
    static {
	try {
	    $method_getDescription_0 = test.basic.basic.rmi.product.Product.class.getMethod("getDescription", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ProductImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getDescription()
    public java.lang.String getDescription()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDescription_0, null, 6422245352532609268L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
