package fei.tools.dc.po;

// Generated Dec 17, 2010 2:03:35 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestTblRadarMsgId generated by hbm2java
 */
@Embeddable
public class TblRadarMsgId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int tradeId;
	private int tradeVer;

	public TblRadarMsgId() {
	}

	public TblRadarMsgId(int tradeId, int tradeVer) {
		this.tradeId = tradeId;
		this.tradeVer = tradeVer;
	}

	@Column(name = "tradeId", nullable = false)
	public int getTradeId() {
		return this.tradeId;
	}

	public void setTradeId(int tradeId) {
		this.tradeId = tradeId;
	}

	@Column(name = "tradeVer", nullable = false)
	public int getTradeVer() {
		return this.tradeVer;
	}

	public void setTradeVer(int tradeVer) {
		this.tradeVer = tradeVer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRadarMsgId))
			return false;
		TblRadarMsgId castOther = (TblRadarMsgId) other;

		return (this.getTradeId() == castOther.getTradeId())
				&& (this.getTradeVer() == castOther.getTradeVer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTradeId();
		result = 37 * result + this.getTradeVer();
		return result;
	}

}
