/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zyf_test_jni_TestJNI */

#ifndef _Included_zyf_test_jni_TestJNI
#define _Included_zyf_test_jni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zyf_test_jni_TestJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zyf_test_jni_TestJNI_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
